name: CI

on: [pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                emacs-version:
                    - 26.3
                    - 29.3

        steps:
            - uses: actions/checkout@v3

            - uses: jcs090218/setup-emacs@master
              with:
                  version: ${{ matrix.emacs-version }}

            - uses: ashutoshvarma/setup-ninja@master

            - name: Run tests
              run: ninja tests
